import type {
  PlayerWeeklyAveragesResponse,
  ParsedMatchup,
  PlayerPredictionsResponse,
} from "@/types/yahoo";

interface TeamMatchupsResponse {
  matchups: Array<ParsedMatchup>;
}

// Mock roster averages data
export const mockRosterAverages: PlayerWeeklyAveragesResponse = {
  roster: [
    {
      name: "Luka Dončić",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "28.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.485", display_name: "FG%" },
            { stat_id: "6", value: "8.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.785", display_name: "FT%" },
            { stat_id: "10", value: "4.2", display_name: "3PTM" },
            { stat_id: "12", value: "33.8", display_name: "PTS" },
            { stat_id: "15", value: "9.5", display_name: "REB" },
            { stat_id: "16", value: "9.2", display_name: "AST" },
            { stat_id: "17", value: "1.5", display_name: "ST" },
            { stat_id: "18", value: "0.3", display_name: "BLK" },
            { stat_id: "19", value: "4.2", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "30.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.492", display_name: "FG%" },
            { stat_id: "6", value: "8.8", display_name: "FTM/A" },
            { stat_id: "8", value: "0.802", display_name: "FT%" },
            { stat_id: "10", value: "4.5", display_name: "3PTM" },
            { stat_id: "12", value: "35.5", display_name: "PTS" },
            { stat_id: "15", value: "10.2", display_name: "REB" },
            { stat_id: "16", value: "10.1", display_name: "AST" },
            { stat_id: "17", value: "1.8", display_name: "ST" },
            { stat_id: "18", value: "0.5", display_name: "BLK" },
            { stat_id: "19", value: "3.8", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "27.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.478", display_name: "FG%" },
            { stat_id: "6", value: "7.9", display_name: "FTM/A" },
            { stat_id: "8", value: "0.771", display_name: "FT%" },
            { stat_id: "10", value: "3.9", display_name: "3PTM" },
            { stat_id: "12", value: "32.1", display_name: "PTS" },
            { stat_id: "15", value: "9.1", display_name: "REB" },
            { stat_id: "16", value: "8.9", display_name: "AST" },
            { stat_id: "17", value: "1.4", display_name: "ST" },
            { stat_id: "18", value: "0.2", display_name: "BLK" },
            { stat_id: "19", value: "4.5", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 28.83, min: 27.8, max: 30.2, standard_deviation: 1.02 },
        { stat_id: "5", display_name: "FG%", average: 0.485, min: 0.478, max: 0.492, standard_deviation: 0.006 },
        { stat_id: "6", display_name: "FTM/A", average: 8.3, min: 7.9, max: 8.8, standard_deviation: 0.38 },
        { stat_id: "8", display_name: "FT%", average: 0.786, min: 0.771, max: 0.802, standard_deviation: 0.013 },
        { stat_id: "10", display_name: "3PTM", average: 4.2, min: 3.9, max: 4.5, standard_deviation: 0.25 },
        { stat_id: "12", display_name: "PTS", average: 33.8, min: 32.1, max: 35.5, standard_deviation: 1.48 },
        { stat_id: "15", display_name: "REB", average: 9.6, min: 9.1, max: 10.2, standard_deviation: 0.48 },
        { stat_id: "16", display_name: "AST", average: 9.4, min: 8.9, max: 10.1, standard_deviation: 0.52 },
        { stat_id: "17", display_name: "ST", average: 1.57, min: 1.4, max: 1.8, standard_deviation: 0.17 },
        { stat_id: "18", display_name: "BLK", average: 0.33, min: 0.2, max: 0.5, standard_deviation: 0.13 },
        { stat_id: "19", display_name: "TO", average: 4.17, min: 3.8, max: 4.5, standard_deviation: 0.29 },
      ],
    },
    {
      name: "Nikola Jokić",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "24.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.582", display_name: "FG%" },
            { stat_id: "6", value: "5.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.815", display_name: "FT%" },
            { stat_id: "10", value: "1.8", display_name: "3PTM" },
            { stat_id: "12", value: "28.5", display_name: "PTS" },
            { stat_id: "15", value: "13.2", display_name: "REB" },
            { stat_id: "16", value: "9.8", display_name: "AST" },
            { stat_id: "17", value: "1.2", display_name: "ST" },
            { stat_id: "18", value: "0.8", display_name: "BLK" },
            { stat_id: "19", value: "3.5", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "25.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.595", display_name: "FG%" },
            { stat_id: "6", value: "5.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.828", display_name: "FT%" },
            { stat_id: "10", value: "2.1", display_name: "3PTM" },
            { stat_id: "12", value: "29.8", display_name: "PTS" },
            { stat_id: "15", value: "13.8", display_name: "REB" },
            { stat_id: "16", value: "10.2", display_name: "AST" },
            { stat_id: "17", value: "1.5", display_name: "ST" },
            { stat_id: "18", value: "1.0", display_name: "BLK" },
            { stat_id: "19", value: "3.2", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "24.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.575", display_name: "FG%" },
            { stat_id: "6", value: "5.0", display_name: "FTM/A" },
            { stat_id: "8", value: "0.810", display_name: "FT%" },
            { stat_id: "10", value: "1.6", display_name: "3PTM" },
            { stat_id: "12", value: "27.9", display_name: "PTS" },
            { stat_id: "15", value: "12.9", display_name: "REB" },
            { stat_id: "16", value: "9.5", display_name: "AST" },
            { stat_id: "17", value: "1.1", display_name: "ST" },
            { stat_id: "18", value: "0.7", display_name: "BLK" },
            { stat_id: "19", value: "3.8", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 24.83, min: 24.2, max: 25.5, standard_deviation: 0.52 },
        { stat_id: "5", display_name: "FG%", average: 0.584, min: 0.575, max: 0.595, standard_deviation: 0.008 },
        { stat_id: "6", display_name: "FTM/A", average: 5.23, min: 5.0, max: 5.5, standard_deviation: 0.21 },
        { stat_id: "8", display_name: "FT%", average: 0.818, min: 0.810, max: 0.828, standard_deviation: 0.007 },
        { stat_id: "10", display_name: "3PTM", average: 1.83, min: 1.6, max: 2.1, standard_deviation: 0.21 },
        { stat_id: "12", display_name: "PTS", average: 28.73, min: 27.9, max: 29.8, standard_deviation: 0.85 },
        { stat_id: "15", display_name: "REB", average: 13.3, min: 12.9, max: 13.8, standard_deviation: 0.38 },
        { stat_id: "16", display_name: "AST", average: 9.83, min: 9.5, max: 10.2, standard_deviation: 0.29 },
        { stat_id: "17", display_name: "ST", average: 1.27, min: 1.1, max: 1.5, standard_deviation: 0.18 },
        { stat_id: "18", display_name: "BLK", average: 0.83, min: 0.7, max: 1.0, standard_deviation: 0.13 },
        { stat_id: "19", display_name: "TO", average: 3.5, min: 3.2, max: 3.8, standard_deviation: 0.25 },
      ],
    },
    {
      name: "Stephen Curry",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "20.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.452", display_name: "FG%" },
            { stat_id: "6", value: "4.8", display_name: "FTM/A" },
            { stat_id: "8", value: "0.925", display_name: "FT%" },
            { stat_id: "10", value: "5.2", display_name: "3PTM" },
            { stat_id: "12", value: "28.5", display_name: "PTS" },
            { stat_id: "15", value: "4.8", display_name: "REB" },
            { stat_id: "16", value: "5.2", display_name: "AST" },
            { stat_id: "17", value: "0.9", display_name: "ST" },
            { stat_id: "18", value: "0.2", display_name: "BLK" },
            { stat_id: "19", value: "3.1", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "22.1", display_name: "FGM/A" },
            { stat_id: "5", value: "0.468", display_name: "FG%" },
            { stat_id: "6", value: "5.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.938", display_name: "FT%" },
            { stat_id: "10", value: "5.8", display_name: "3PTM" },
            { stat_id: "12", value: "30.2", display_name: "PTS" },
            { stat_id: "15", value: "5.2", display_name: "REB" },
            { stat_id: "16", value: "5.8", display_name: "AST" },
            { stat_id: "17", value: "1.1", display_name: "ST" },
            { stat_id: "18", value: "0.3", display_name: "BLK" },
            { stat_id: "19", value: "2.9", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "19.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.445", display_name: "FG%" },
            { stat_id: "6", value: "4.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.920", display_name: "FT%" },
            { stat_id: "10", value: "4.9", display_name: "3PTM" },
            { stat_id: "12", value: "27.1", display_name: "PTS" },
            { stat_id: "15", value: "4.5", display_name: "REB" },
            { stat_id: "16", value: "4.9", display_name: "AST" },
            { stat_id: "17", value: "0.8", display_name: "ST" },
            { stat_id: "18", value: "0.1", display_name: "BLK" },
            { stat_id: "19", value: "3.3", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 20.8, min: 19.8, max: 22.1, standard_deviation: 0.95 },
        { stat_id: "5", display_name: "FG%", average: 0.455, min: 0.445, max: 0.468, standard_deviation: 0.010 },
        { stat_id: "6", display_name: "FTM/A", average: 4.83, min: 4.5, max: 5.2, standard_deviation: 0.29 },
        { stat_id: "8", display_name: "FT%", average: 0.928, min: 0.920, max: 0.938, standard_deviation: 0.007 },
        { stat_id: "10", display_name: "3PTM", average: 5.3, min: 4.9, max: 5.8, standard_deviation: 0.38 },
        { stat_id: "12", display_name: "PTS", average: 28.6, min: 27.1, max: 30.2, standard_deviation: 1.35 },
        { stat_id: "15", display_name: "REB", average: 4.83, min: 4.5, max: 5.2, standard_deviation: 0.29 },
        { stat_id: "16", display_name: "AST", average: 5.3, min: 4.9, max: 5.8, standard_deviation: 0.38 },
        { stat_id: "17", display_name: "ST", average: 0.93, min: 0.8, max: 1.1, standard_deviation: 0.13 },
        { stat_id: "18", display_name: "BLK", average: 0.2, min: 0.1, max: 0.3, standard_deviation: 0.08 },
        { stat_id: "19", display_name: "TO", average: 3.1, min: 2.9, max: 3.3, standard_deviation: 0.16 },
      ],
    },
    {
      name: "Giannis Antetokounmpo",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "26.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.612", display_name: "FG%" },
            { stat_id: "6", value: "9.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.658", display_name: "FT%" },
            { stat_id: "10", value: "1.2", display_name: "3PTM" },
            { stat_id: "12", value: "32.8", display_name: "PTS" },
            { stat_id: "15", value: "11.5", display_name: "REB" },
            { stat_id: "16", value: "6.2", display_name: "AST" },
            { stat_id: "17", value: "1.1", display_name: "ST" },
            { stat_id: "18", value: "1.2", display_name: "BLK" },
            { stat_id: "19", value: "4.2", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "27.1", display_name: "FGM/A" },
            { stat_id: "5", value: "0.625", display_name: "FG%" },
            { stat_id: "6", value: "10.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.671", display_name: "FT%" },
            { stat_id: "10", value: "1.5", display_name: "3PTM" },
            { stat_id: "12", value: "34.5", display_name: "PTS" },
            { stat_id: "15", value: "12.1", display_name: "REB" },
            { stat_id: "16", value: "6.8", display_name: "AST" },
            { stat_id: "17", value: "1.3", display_name: "ST" },
            { stat_id: "18", value: "1.4", display_name: "BLK" },
            { stat_id: "19", value: "3.9", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "25.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.605", display_name: "FG%" },
            { stat_id: "6", value: "9.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.652", display_name: "FT%" },
            { stat_id: "10", value: "1.0", display_name: "3PTM" },
            { stat_id: "12", value: "31.9", display_name: "PTS" },
            { stat_id: "15", value: "11.2", display_name: "REB" },
            { stat_id: "16", value: "5.9", display_name: "AST" },
            { stat_id: "17", value: "1.0", display_name: "ST" },
            { stat_id: "18", value: "1.1", display_name: "BLK" },
            { stat_id: "19", value: "4.5", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 26.37, min: 25.8, max: 27.1, standard_deviation: 0.55 },
        { stat_id: "5", display_name: "FG%", average: 0.614, min: 0.605, max: 0.625, standard_deviation: 0.008 },
        { stat_id: "6", display_name: "FTM/A", average: 9.63, min: 9.2, max: 10.2, standard_deviation: 0.42 },
        { stat_id: "8", display_name: "FT%", average: 0.660, min: 0.652, max: 0.671, standard_deviation: 0.008 },
        { stat_id: "10", display_name: "3PTM", average: 1.23, min: 1.0, max: 1.5, standard_deviation: 0.21 },
        { stat_id: "12", display_name: "PTS", average: 33.07, min: 31.9, max: 34.5, standard_deviation: 1.10 },
        { stat_id: "15", display_name: "REB", average: 11.6, min: 11.2, max: 12.1, standard_deviation: 0.38 },
        { stat_id: "16", display_name: "AST", average: 6.3, min: 5.9, max: 6.8, standard_deviation: 0.38 },
        { stat_id: "17", display_name: "ST", average: 1.13, min: 1.0, max: 1.3, standard_deviation: 0.13 },
        { stat_id: "18", display_name: "BLK", average: 1.23, min: 1.1, max: 1.4, standard_deviation: 0.13 },
        { stat_id: "19", display_name: "TO", average: 4.2, min: 3.9, max: 4.5, standard_deviation: 0.25 },
      ],
    },
    {
      name: "Jayson Tatum",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "23.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.478", display_name: "FG%" },
            { stat_id: "6", value: "6.8", display_name: "FTM/A" },
            { stat_id: "8", value: "0.815", display_name: "FT%" },
            { stat_id: "10", value: "3.8", display_name: "3PTM" },
            { stat_id: "12", value: "28.2", display_name: "PTS" },
            { stat_id: "15", value: "8.5", display_name: "REB" },
            { stat_id: "16", value: "4.8", display_name: "AST" },
            { stat_id: "17", value: "1.0", display_name: "ST" },
            { stat_id: "18", value: "0.5", display_name: "BLK" },
            { stat_id: "19", value: "2.8", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "24.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.485", display_name: "FG%" },
            { stat_id: "6", value: "7.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.828", display_name: "FT%" },
            { stat_id: "10", value: "4.1", display_name: "3PTM" },
            { stat_id: "12", value: "29.5", display_name: "PTS" },
            { stat_id: "15", value: "9.0", display_name: "REB" },
            { stat_id: "16", value: "5.2", display_name: "AST" },
            { stat_id: "17", value: "1.2", display_name: "ST" },
            { stat_id: "18", value: "0.6", display_name: "BLK" },
            { stat_id: "19", value: "2.6", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "22.9", display_name: "FGM/A" },
            { stat_id: "5", value: "0.472", display_name: "FG%" },
            { stat_id: "6", value: "6.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.808", display_name: "FT%" },
            { stat_id: "10", value: "3.5", display_name: "3PTM" },
            { stat_id: "12", value: "27.1", display_name: "PTS" },
            { stat_id: "15", value: "8.2", display_name: "REB" },
            { stat_id: "16", value: "4.5", display_name: "AST" },
            { stat_id: "17", value: "0.9", display_name: "ST" },
            { stat_id: "18", value: "0.4", display_name: "BLK" },
            { stat_id: "19", value: "3.0", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 23.53, min: 22.9, max: 24.2, standard_deviation: 0.55 },
        { stat_id: "5", display_name: "FG%", average: 0.478, min: 0.472, max: 0.485, standard_deviation: 0.005 },
        { stat_id: "6", display_name: "FTM/A", average: 6.83, min: 6.5, max: 7.2, standard_deviation: 0.29 },
        { stat_id: "8", display_name: "FT%", average: 0.817, min: 0.808, max: 0.828, standard_deviation: 0.008 },
        { stat_id: "10", display_name: "3PTM", average: 3.8, min: 3.5, max: 4.1, standard_deviation: 0.25 },
        { stat_id: "12", display_name: "PTS", average: 28.27, min: 27.1, max: 29.5, standard_deviation: 1.02 },
        { stat_id: "15", display_name: "REB", average: 8.57, min: 8.2, max: 9.0, standard_deviation: 0.35 },
        { stat_id: "16", display_name: "AST", average: 4.83, min: 4.5, max: 5.2, standard_deviation: 0.29 },
        { stat_id: "17", display_name: "ST", average: 1.03, min: 0.9, max: 1.2, standard_deviation: 0.13 },
        { stat_id: "18", display_name: "BLK", average: 0.5, min: 0.4, max: 0.6, standard_deviation: 0.08 },
        { stat_id: "19", display_name: "TO", average: 2.8, min: 2.6, max: 3.0, standard_deviation: 0.17 },
      ],
    },
    {
      name: "Anthony Edwards",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "22.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.465", display_name: "FG%" },
            { stat_id: "6", value: "5.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.842", display_name: "FT%" },
            { stat_id: "10", value: "3.2", display_name: "3PTM" },
            { stat_id: "12", value: "26.8", display_name: "PTS" },
            { stat_id: "15", value: "5.8", display_name: "REB" },
            { stat_id: "16", value: "5.2", display_name: "AST" },
            { stat_id: "17", value: "1.3", display_name: "ST" },
            { stat_id: "18", value: "0.6", display_name: "BLK" },
            { stat_id: "19", value: "3.2", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "23.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.472", display_name: "FG%" },
            { stat_id: "6", value: "5.8", display_name: "FTM/A" },
            { stat_id: "8", value: "0.855", display_name: "FT%" },
            { stat_id: "10", value: "3.5", display_name: "3PTM" },
            { stat_id: "12", value: "27.8", display_name: "PTS" },
            { stat_id: "15", value: "6.2", display_name: "REB" },
            { stat_id: "16", value: "5.5", display_name: "AST" },
            { stat_id: "17", value: "1.5", display_name: "ST" },
            { stat_id: "18", value: "0.7", display_name: "BLK" },
            { stat_id: "19", value: "3.0", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "22.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.458", display_name: "FG%" },
            { stat_id: "6", value: "5.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.835", display_name: "FT%" },
            { stat_id: "10", value: "3.0", display_name: "3PTM" },
            { stat_id: "12", value: "26.1", display_name: "PTS" },
            { stat_id: "15", value: "5.5", display_name: "REB" },
            { stat_id: "16", value: "4.9", display_name: "AST" },
            { stat_id: "17", value: "1.2", display_name: "ST" },
            { stat_id: "18", value: "0.5", display_name: "BLK" },
            { stat_id: "19", value: "3.4", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 22.83, min: 22.2, max: 23.5, standard_deviation: 0.55 },
        { stat_id: "5", display_name: "FG%", average: 0.465, min: 0.458, max: 0.472, standard_deviation: 0.006 },
        { stat_id: "6", display_name: "FTM/A", average: 5.5, min: 5.2, max: 5.8, standard_deviation: 0.25 },
        { stat_id: "8", display_name: "FT%", average: 0.844, min: 0.835, max: 0.855, standard_deviation: 0.008 },
        { stat_id: "10", display_name: "3PTM", average: 3.23, min: 3.0, max: 3.5, standard_deviation: 0.21 },
        { stat_id: "12", display_name: "PTS", average: 26.9, min: 26.1, max: 27.8, standard_deviation: 0.72 },
        { stat_id: "15", display_name: "REB", average: 5.83, min: 5.5, max: 6.2, standard_deviation: 0.29 },
        { stat_id: "16", display_name: "AST", average: 5.2, min: 4.9, max: 5.5, standard_deviation: 0.25 },
        { stat_id: "17", display_name: "ST", average: 1.33, min: 1.2, max: 1.5, standard_deviation: 0.13 },
        { stat_id: "18", display_name: "BLK", average: 0.6, min: 0.5, max: 0.7, standard_deviation: 0.08 },
        { stat_id: "19", display_name: "TO", average: 3.2, min: 3.0, max: 3.4, standard_deviation: 0.17 },
      ],
    },
    {
      name: "Joel Embiid",
      image_url: "/images/avatar.webp",
      status: "O",
      status_full: "Out",
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "25.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.535", display_name: "FG%" },
            { stat_id: "6", value: "10.5", display_name: "FTM/A" },
            { stat_id: "8", value: "0.882", display_name: "FT%" },
            { stat_id: "10", value: "1.5", display_name: "3PTM" },
            { stat_id: "12", value: "33.8", display_name: "PTS" },
            { stat_id: "15", value: "11.2", display_name: "REB" },
            { stat_id: "16", value: "5.5", display_name: "AST" },
            { stat_id: "17", value: "1.0", display_name: "ST" },
            { stat_id: "18", value: "1.8", display_name: "BLK" },
            { stat_id: "19", value: "3.8", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "26.1", display_name: "FGM/A" },
            { stat_id: "5", value: "0.548", display_name: "FG%" },
            { stat_id: "6", value: "11.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.892", display_name: "FT%" },
            { stat_id: "10", value: "1.8", display_name: "3PTM" },
            { stat_id: "12", value: "35.2", display_name: "PTS" },
            { stat_id: "15", value: "11.8", display_name: "REB" },
            { stat_id: "16", value: "5.9", display_name: "AST" },
            { stat_id: "17", value: "1.2", display_name: "ST" },
            { stat_id: "18", value: "2.0", display_name: "BLK" },
            { stat_id: "19", value: "3.5", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "24.8", display_name: "FGM/A" },
            { stat_id: "5", value: "0.528", display_name: "FG%" },
            { stat_id: "6", value: "10.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.875", display_name: "FT%" },
            { stat_id: "10", value: "1.4", display_name: "3PTM" },
            { stat_id: "12", value: "32.9", display_name: "PTS" },
            { stat_id: "15", value: "10.9", display_name: "REB" },
            { stat_id: "16", value: "5.2", display_name: "AST" },
            { stat_id: "17", value: "0.9", display_name: "ST" },
            { stat_id: "18", value: "1.7", display_name: "BLK" },
            { stat_id: "19", value: "4.0", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 25.37, min: 24.8, max: 26.1, standard_deviation: 0.55 },
        { stat_id: "5", display_name: "FG%", average: 0.537, min: 0.528, max: 0.548, standard_deviation: 0.008 },
        { stat_id: "6", display_name: "FTM/A", average: 10.63, min: 10.2, max: 11.2, standard_deviation: 0.42 },
        { stat_id: "8", display_name: "FT%", average: 0.883, min: 0.875, max: 0.892, standard_deviation: 0.007 },
        { stat_id: "10", display_name: "3PTM", average: 1.57, min: 1.4, max: 1.8, standard_deviation: 0.17 },
        { stat_id: "12", display_name: "PTS", average: 33.97, min: 32.9, max: 35.2, standard_deviation: 1.02 },
        { stat_id: "15", display_name: "REB", average: 11.3, min: 10.9, max: 11.8, standard_deviation: 0.38 },
        { stat_id: "16", display_name: "AST", average: 5.53, min: 5.2, max: 5.9, standard_deviation: 0.29 },
        { stat_id: "17", display_name: "ST", average: 1.03, min: 0.9, max: 1.2, standard_deviation: 0.13 },
        { stat_id: "18", display_name: "BLK", average: 1.83, min: 1.7, max: 2.0, standard_deviation: 0.13 },
        { stat_id: "19", display_name: "TO", average: 3.77, min: 3.5, max: 4.0, standard_deviation: 0.21 },
      ],
    },
    {
      name: "Shai Gilgeous-Alexander",
      image_url: "/images/avatar.webp",
      status: undefined,
      status_full: undefined,
      weekly_stats: [
        {
          week: 1,
          stats: [
            { stat_id: "1", value: "24.5", display_name: "FGM/A" },
            { stat_id: "5", value: "0.542", display_name: "FG%" },
            { stat_id: "6", value: "8.2", display_name: "FTM/A" },
            { stat_id: "8", value: "0.915", display_name: "FT%" },
            { stat_id: "10", value: "1.8", display_name: "3PTM" },
            { stat_id: "12", value: "31.2", display_name: "PTS" },
            { stat_id: "15", value: "5.5", display_name: "REB" },
            { stat_id: "16", value: "6.2", display_name: "AST" },
            { stat_id: "17", value: "2.1", display_name: "ST" },
            { stat_id: "18", value: "0.8", display_name: "BLK" },
            { stat_id: "19", value: "2.5", display_name: "TO" },
          ],
        },
        {
          week: 2,
          stats: [
            { stat_id: "1", value: "25.2", display_name: "FGM/A" },
            { stat_id: "5", value: "0.552", display_name: "FG%" },
            { stat_id: "6", value: "8.8", display_name: "FTM/A" },
            { stat_id: "8", value: "0.925", display_name: "FT%" },
            { stat_id: "10", value: "2.1", display_name: "3PTM" },
            { stat_id: "12", value: "32.5", display_name: "PTS" },
            { stat_id: "15", value: "5.8", display_name: "REB" },
            { stat_id: "16", value: "6.5", display_name: "AST" },
            { stat_id: "17", value: "2.3", display_name: "ST" },
            { stat_id: "18", value: "0.9", display_name: "BLK" },
            { stat_id: "19", value: "2.3", display_name: "TO" },
          ],
        },
        {
          week: 3,
          stats: [
            { stat_id: "1", value: "23.9", display_name: "FGM/A" },
            { stat_id: "5", value: "0.535", display_name: "FG%" },
            { stat_id: "6", value: "7.9", display_name: "FTM/A" },
            { stat_id: "8", value: "0.908", display_name: "FT%" },
            { stat_id: "10", value: "1.6", display_name: "3PTM" },
            { stat_id: "12", value: "30.5", display_name: "PTS" },
            { stat_id: "15", value: "5.2", display_name: "REB" },
            { stat_id: "16", value: "5.9", display_name: "AST" },
            { stat_id: "17", value: "1.9", display_name: "ST" },
            { stat_id: "18", value: "0.7", display_name: "BLK" },
            { stat_id: "19", value: "2.7", display_name: "TO" },
          ],
        },
      ],
      aggregated_stats: [
        { stat_id: "1", display_name: "FGM/A", average: 24.53, min: 23.9, max: 25.2, standard_deviation: 0.55 },
        { stat_id: "5", display_name: "FG%", average: 0.543, min: 0.535, max: 0.552, standard_deviation: 0.007 },
        { stat_id: "6", display_name: "FTM/A", average: 8.3, min: 7.9, max: 8.8, standard_deviation: 0.38 },
        { stat_id: "8", display_name: "FT%", average: 0.916, min: 0.908, max: 0.925, standard_deviation: 0.007 },
        { stat_id: "10", display_name: "3PTM", average: 1.83, min: 1.6, max: 2.1, standard_deviation: 0.21 },
        { stat_id: "12", display_name: "PTS", average: 31.4, min: 30.5, max: 32.5, standard_deviation: 0.85 },
        { stat_id: "15", display_name: "REB", average: 5.5, min: 5.2, max: 5.8, standard_deviation: 0.25 },
        { stat_id: "16", display_name: "AST", average: 6.2, min: 5.9, max: 6.5, standard_deviation: 0.25 },
        { stat_id: "17", display_name: "ST", average: 2.1, min: 1.9, max: 2.3, standard_deviation: 0.17 },
        { stat_id: "18", display_name: "BLK", average: 0.8, min: 0.7, max: 0.9, standard_deviation: 0.08 },
        { stat_id: "19", display_name: "TO", average: 2.5, min: 2.3, max: 2.7, standard_deviation: 0.17 },
      ],
    },
  ],
};

// Mock matchups data
export const mockMatchups: TeamMatchupsResponse = {
  matchups: [
    {
      week: 1,
      week_start: "2024-10-22",
      week_end: "2024-10-28",
      status: "postevent",
      winner_team_key: "423.l.123456.t.1",
      opponent_team_key: "423.l.123456.t.2",
      team_stats: [
        { stat: { stat_id: "1", value: "185.2", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.485", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "58.5", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.815", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "28.5", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "245.8", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "98.2", display_name: "REB" } },
        { stat: { stat_id: "16", value: "68.5", display_name: "AST" } },
        { stat: { stat_id: "17", value: "12.5", display_name: "ST" } },
        { stat: { stat_id: "18", value: "8.2", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "28.5", display_name: "TO" } },
      ],
      opponent_stats: [
        { stat: { stat_id: "1", value: "172.8", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.462", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "52.2", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.785", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "24.8", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "228.5", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "92.5", display_name: "REB" } },
        { stat: { stat_id: "16", value: "62.2", display_name: "AST" } },
        { stat: { stat_id: "17", value: "10.8", display_name: "ST" } },
        { stat: { stat_id: "18", value: "7.5", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "32.2", display_name: "TO" } },
      ],
    },
    {
      week: 2,
      week_start: "2024-10-29",
      week_end: "2024-11-04",
      status: "postevent",
      winner_team_key: "423.l.123456.t.1",
      opponent_team_key: "423.l.123456.t.3",
      team_stats: [
        { stat: { stat_id: "1", value: "192.5", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.492", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "62.2", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.828", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "31.2", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "258.5", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "102.5", display_name: "REB" } },
        { stat: { stat_id: "16", value: "72.8", display_name: "AST" } },
        { stat: { stat_id: "17", value: "14.2", display_name: "ST" } },
        { stat: { stat_id: "18", value: "9.5", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "26.8", display_name: "TO" } },
      ],
      opponent_stats: [
        { stat: { stat_id: "1", value: "178.5", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.468", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "55.8", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.798", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "26.5", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "235.2", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "95.8", display_name: "REB" } },
        { stat: { stat_id: "16", value: "65.5", display_name: "AST" } },
        { stat: { stat_id: "17", value: "11.5", display_name: "ST" } },
        { stat: { stat_id: "18", value: "8.2", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "30.5", display_name: "TO" } },
      ],
    },
    {
      week: 3,
      week_start: "2024-11-05",
      week_end: "2024-11-11",
      status: "postevent",
      winner_team_key: "423.l.123456.t.4",
      opponent_team_key: "423.l.123456.t.1",
      team_stats: [
        { stat: { stat_id: "1", value: "178.2", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.478", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "55.5", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.808", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "26.8", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "238.2", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "95.5", display_name: "REB" } },
        { stat: { stat_id: "16", value: "64.2", display_name: "AST" } },
        { stat: { stat_id: "17", value: "11.2", display_name: "ST" } },
        { stat: { stat_id: "18", value: "7.8", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "30.2", display_name: "TO" } },
      ],
      opponent_stats: [
        { stat: { stat_id: "1", value: "188.5", display_name: "FGM/A" } },
        { stat: { stat_id: "5", value: "0.488", display_name: "FG%" } },
        { stat: { stat_id: "6", value: "60.8", display_name: "FTM/A" } },
        { stat: { stat_id: "8", value: "0.822", display_name: "FT%" } },
        { stat: { stat_id: "10", value: "29.5", display_name: "3PTM" } },
        { stat: { stat_id: "12", value: "252.5", display_name: "PTS" } },
        { stat: { stat_id: "15", value: "100.2", display_name: "REB" } },
        { stat: { stat_id: "16", value: "70.5", display_name: "AST" } },
        { stat: { stat_id: "17", value: "13.5", display_name: "ST" } },
        { stat: { stat_id: "18", value: "9.2", display_name: "BLK" } },
        { stat: { stat_id: "19", value: "27.5", display_name: "TO" } },
      ],
    },
  ],
};

// Mock roster data (current week stats)
export const mockRoster = {
  roster: mockRosterAverages.roster.map((player) => ({
    name: player.name,
    image_url: player.image_url,
    status: player.status,
    status_full: player.status_full,
    stats: player.aggregated_stats?.map((stat) => ({
      stat_id: stat.stat_id,
      value: stat.average?.toFixed(1) || "-",
      display_name: stat.display_name,
    })) || [],
  })),
};

// Mock predictions data
export const mockPredictions: PlayerPredictionsResponse = {
  target_week: 4,
  roster: mockRosterAverages.roster.map((player, playerIndex) => ({
    name: player.name,
    image_url: player.image_url,
    status: player.status,
    status_full: player.status_full,
    has_sufficient_data: true,
    predicted_stats: player.aggregated_stats?.map((stat, statIndex) => {
      // Generate predictions based on averages with deterministic variation
      const baseValue = stat.average || 0;
      const variation = baseValue * 0.05; // 5% variation
      // Use deterministic seed based on player and stat index
      const seed = (playerIndex * 10 + statIndex) % 7;
      const variationFactor = (seed - 3) / 3; // Range from -1 to 1
      const predictedValue = baseValue + variationFactor * variation;
      const confidenceInterval = baseValue * 0.1; // 10% confidence interval
      
      // Determine trend deterministically
      const trendSeed = (playerIndex + statIndex) % 3;
      let trend: "improving" | "stable" | "declining" = "stable";
      if (trendSeed === 0) trend = "improving";
      else if (trendSeed === 1) trend = "declining";

      return {
        stat_id: stat.stat_id,
        display_name: stat.display_name,
        predicted_value: predictedValue,
        confidence_interval: confidenceInterval,
        trend,
      };
    }) || [],
  })),
};

